version: "3.8"

services:
  craft:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./craft:/var/www/craft
    ports:
      - "8081:80"
    environment:
      CRAFT_ENVIRONMENT: dev
    depends_on:
      - craftdb
    networks:
      - craftnet

  craftdb:
    image: mariadb:10.5
    ports:
      - "33064:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: craft_local
      MYSQL_USER: craft
      MYSQL_PASSWORD: secret
    volumes:
      - craftdb_data:/var/lib/mysql
    networks:
      - craftnet

networks:
  craftnet:
    driver: bridge

volumes:
  craftdb_data:
    driver: local
