color: null
fieldLayouts:
  9db7986d-aa52-4480-8366-6be20e817784:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-02T13:23:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2e9c8bc5-d841-47c4-ac41-31ad8aa0eda1
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 900d7845-f830-4e9a-b233-070538c6364a
        userCondition: null
handle: blockNews
hasTitleField: true
icon: list
name: 'Block News'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
