color: sky
fieldLayouts:
  2acb862c-f8b1-4dd0-af64-1f29283a73b9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-20T21:12:34+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Titel
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8acb4111-22df-4cf4-b5a4-8782f81a16f5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-20T21:46:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 25bc04c9-5ac2-468a-a2df-6a0c5c22258f # Im Menü anzeigen
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1421b0cc-c815-41ad-bb8f-45ee3c2c9635
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-05-06T10:37:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 745270c2-203f-4a46-82bc-3e4556145e25 # Im Header anzeigen
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0885818-c95c-42a9-9179-aa3632fbda38
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-04-20T21:46:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b8942796-6b3f-40a3-9ec0-7175edff4533 # Im Footer anzeigen
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0de88add-1f83-4bfd-adfb-badbb311bdfa
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-04-20T21:46:02+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\LineBreak
            uid: 29669140-2ef3-4f3d-a041-0ae5bf2b25e1
            userCondition: null
          -
            dateAdded: '2025-04-20T21:35:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f6da7d8c-6a08-412e-ba9f-563221bc7e4a # Blöcke
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f308c1e5-1f6d-4959-8be6-27018f543933
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 02084f02-1afb-4a11-8386-ebd88585f1b3
        userCondition: null
handle: pages
hasTitleField: true
icon: memo
name: Seiten
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
