color: null
fieldLayouts:
  424b39d9-332c-4a1a-a3e3-533bc590032e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-20T21:41:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d8f66a42-78bf-450c-983b-2ad16a0b59b2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-20T21:43:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 85aaa9bf-8bf2-449e-b9f2-4bbad862e5fc # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ceb72e3b-490e-46ec-8a13-032fe6fa4afa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ac1217a1-c19f-427b-932b-2c37da52072e
        userCondition: null
handle: subblockAccordion
hasTitleField: true
icon: null
name: 'Subblock Accordion'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
