columnSuffix: null
handle: imageDisplay
instructions: null
name: Bildanzeige
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Einzelbild
        -
          - value
          - single
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Einzelbild Quadrat klein'
        -
          - value
          - singleSmallSquare
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '3er Bild'
        -
          - value
          - triple
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
