columnSuffix: null
handle: text
instructions: null
name: Text
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: f2c3d145-c0bd-4091-af1d-c410c9a5c650 # Simple
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
