defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: bb16ce0c-3242-43c9-9ff1-22f09f40931c # News
handle: news
maxAuthors: 1
name: News
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  fa695097-4e18-48d3-9ad2-34bbc680677d: # farbcode-base
    enabledByDefault: true
    hasUrls: true
    template: news/_entry.twig
    uriFormat: 'news/{slug}'
type: channel
