# Diese GitHub Action führt ein automatisiertes Update für Craft CMS durch.
# Dabei werden folgende Schritte ausgeführt:
# - Abhängigkeiten installieren
# - Datenbank-Backup über Craft CLI
# - Craft CMS Update
# - Composer-Abhängigkeiten aktualisieren
# - Health Check
# - Änderungen committen und ein Pull Request erstellen (nur bei Änderungen)

name: Automatisches Craft CMS Update

on:
    # Ermöglicht manuelles Auslösen über die GitHub UI
    workflow_dispatch:

    # Unterstützt automatisiertes Triggern via repository_dispatch (z.B. über n8n)
    repository_dispatch:
        types: [run-backup-und-update]
        branches:
            - main

jobs:
    update:
        runs-on: ubuntu-latest # Verwende den neuesten Ubuntu-Runner

        steps:
            # 🔁 Schritt 1: Repository auschecken (Quellcode holen)
            - name: Projekt auschecken
              uses: actions/checkout@v4

            # 🛠️ Schritt 2: PHP + Composer einrichten
            - name: PHP und Composer installieren
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2' # Stelle sicher, dass die PHP-Version zu Craft passt
                  extensions: mbstring, intl, zip, pdo_mysql # Notwendige PHP-Erweiterungen
                  tools: composer # Composer installieren

            # 📦 Schritt 3: Abhängigkeiten installieren (aktueller Stand aus composer.lock)
            - name: Composer-Abhängigkeiten installieren
              run: composer install --no-interaction

            # 💾 Schritt 4: Datenbank-Backup via Craft CLI
            - name: 💾 Datenbank-Backup (Craft CLI)
              run: |
                  echo "Starte Craft-Backup..."
                  php craft db/backup ./my-backups/ || (echo "❌ Backup fehlgeschlagen" && exit 1)

            # 🔄 Schritt 5: Craft CMS Update ausführen (non-blocking Fehlerbehandlung)
            - name: ⬆️ Craft CMS Update ausführen
              run: |
                  echo "Starte Craft Update..."
                  php craft update all || echo "⚠️ Fehler bei Craft Update (ignoriert für Testzwecke)"

            # 🧱 Schritt 6: Composer-Abhängigkeiten aktualisieren (Dependencies)
            - name: ⬆️ Composer-Abhängigkeiten aktualisieren
              run: |
                  echo "Starte Composer Update..."
                  composer update --no-interaction

            - name: Health Check (optional)
              run: |
               echo "Starte Health Check auf ${{ env.HEALTH_CHECK_URL }}"
               curl -f ${{ env.HEALTH_CHECK_URL }} || (echo '❌ Health Check fehlgeschlagen' && exit 1)
              env:
               HEALTH_CHECK_URL: http://farbcode-base.test/cms/health.php

                
                
            # 🚀 Schritt 8: Änderungen committen + PR erstellen (nur bei Änderungen)
            - name: 📤 Änderungen committen und Pull Request erstellen
              uses: peter-evans/create-pull-request@v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }} # Automatische Authentifizierung
                  commit-message: "📦 Update Craft CMS Abhängigkeiten"
                  title: "⬆️ Automatisches Craft CMS Update"
                  body: |
                      Dieses Update wurde automatisch erstellt.
                      Bitte prüfe ob die Website nach dem Update fehlerfrei läuft.
                  branch: update/craft
                  delete-branch: true
