name: Craft CMS Update (Clean)

on:
  workflow_dispatch:
    inputs:
      skip_backup:
        description: 'Skip backup'
        type: boolean
        default: false
      dry_run:
        description: 'Dry run only'
        type: boolean
        default: false
  repository_dispatch:
    types: [run-backup-und-update]

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    permissions:
      contents: write
      pull-requests: write
      issues: write
    
    services:
      # ... dein services-Block bleibt unverändert ...
      mysql:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: craft_local
          MYSQL_USER: craft
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, zip, pdo_mysql, gd, curl
          tools: composer, jq # jq hinzugefügt, um JSON zu verarbeiten

      - name: Install Dependencies
        working-directory: ./craft
        run: |
          composer install --no-interaction --optimize-autoloader --prefer-dist
          
      # =========================================================================
      # NEUER SCHRITT: Updates ermitteln und Zusammenfassung erstellen
      # Dieser Schritt kommt VOR dem eigentlichen Update.
      # =========================================================================
      - name: Check for updates and generate summary
        id: update_summary
        working-directory: ./craft
        run: |
          # Führe 'composer outdated' aus und hole die direkten Abhängigkeiten als JSON
          # Die Pipe zu '|| true' verhindert einen Fehler, falls keine Updates da sind
          updates_json=$(composer outdated --direct --format=json || true)
          
          # Verarbeite das JSON mit 'jq' zu einer lesbaren Markdown-Liste
          # Wenn keine Updates da sind, wird ein entsprechender Text generiert
          summary=$(echo "$updates_json" | jq -r '.installed | if length > 0 then map("• `\(.name)` (\(.version) → \(.latest))") | .[] else "No direct dependency updates found." end')
          
          # Speichere die mehrzeilige Zusammenfassung als Output für den PR-Schritt
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$summary" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # ... die Schritte Setup Environment, Health Check, Create Backup bleiben unverändert ...
      - name: Setup Environment
        # ...
      - name: Health Check
        # ...
      - name: Create Backup
        # ...

      - name: Run Update
        working-directory: ./craft
        run: |
          if [ "${{ inputs.dry_run }}" = "true" ]; then
            echo "Dry run - showing available updates"
            php craft update/info || echo "Update info not available"
          else
            echo "Running Craft update"
            php craft update all --interactive=0 --backup=0 || echo "Update completed with warnings"
            composer update --no-interaction || echo "Composer update completed with warnings"
          fi
          
      # ... die Schritte Clear Cache, Final Health Check bleiben unverändert ...
      - name: Clear Cache
        # ...
      - name: Final Health Check
        # ...

      # =========================================================================
      # ANGEPASSTER SCHRITT: Pull Request mit sinnvollen Infos erstellen
      # =========================================================================
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          # Du brauchst das Token hier nicht extra angeben
          branch: update/craft-run-${{ github.run_number }}
          delete-branch: true
          
          # Ein sinnvollerer, fester Commit-Titel
          commit-message: "chore(deps): Update Craft CMS & Composer dependencies"

          # Ein besserer, fester PR-Titel im "Conventional Commits"-Stil
          title: "chore(deps): Update Composer dependencies"
          
          # Der neue PR-Body, der die Zusammenfassung enthält
          body: |
            ## 🤖 Automated Dependency Update
            
            This PR was automatically generated and contains the latest updates for your project's dependencies.
            
            ### Changes
            ${{ steps.update_summary.outputs.summary }}
            
            ---
            
            ### Run Details
            - **Trigger:** `${{ github.event_name }}`
            - **Backup created:** `${{ !inputs.skip_backup && '✅' || '⏭️' }}`
            - **Dry run:** `${{ inputs.dry_run && '🧪' || '✅' }}`
            - **Workflow Run:** [View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            
            **Next steps:**
            - Review changes
            - Test on staging
            - Merge for production deployment
          labels: |
            craft-update
            automated
