name: craft-prod-mini

on:
  workflow_dispatch:
    inputs:
      envoyer:
        description: 'Envoyer ausführen'
        type: boolean
        default: true

permissions:
  contents: read

concurrency:
  group: prod-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      PROD_HEALTH_URL: ${{ secrets.PROD_HEALTH_URL }}
      PROD_ROOT_URL: ${{ secrets.PROD_ROOT_URL }}
      ENVOYER_HOOK_URL: ${{ secrets.ENVOYER_HOOK_URL }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Pre-Health
        run: |
          curl --fail --silent --show-error --max-time 20 "$PROD_HEALTH_URL" | jq -e '.status=="ok"'

      - name: Envoyer deploy
        if: ${{ inputs.envoyer || inputs.envoyer == 'true' }}
        run: |
          curl --fail --silent --show-error --max-time 20 --retry 3 --retry-connrefused -X POST "$ENVOYER_HOOK_URL"

      - name: Warten bis gesund
        run: |
          end=$((SECONDS+600))
          ok=0
          while [ $SECONDS -lt $end ]; do
            if curl --fail --silent --show-error --max-time 20 "$PROD_HEALTH_URL" | jq -e '.status=="ok"' >/dev/null && \
               [ "$(curl --fail --silent --show-error --max-time 20 -o /dev/null -w "%{http_code}\n" "$PROD_ROOT_URL")" = "200" ]; then
              ok=1; break
            fi
            sleep 10
          done
          test $ok -eq 1

      - name: Fertig
        run: echo "Production ok"
