name: Craft CMS Backup & Update

on:
  repository_dispatch:
    types: [run-backup-und-update]

jobs:
  backup-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Test Message
        run: echo "Webhook trigger erfolgreich empfangen."
