name: Run Backup und Update

on:
  repository_dispatch:
    types: [run-backup-und-update]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo, mysql
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run Craft Health Check
        run: php craft/web/health.php

      - name: Backup DB
        run: php craft/craft db/backup ./backups/

      - name: Update Craft CMS
        run: php craft/craft update all
